services:
  - type: web
    name: novara-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    headers:
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /images/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /videos/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.css
        name: Cache-Control
        value: public, max-age=31536000, immutable
